[build]
command = "pip install -r requirements.txt && streamlit run app.py"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.9"

[dev]
command = "streamlit run app.py"
port = 8501

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
status = 200

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[functions]
directory = "functions/"
node_bundler = "esbuild"